# Generated by Django 3.0.7 on 2020-06-13 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(default='', max_length=200)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('answerA', models.TextField(default='')),
                ('answerB', models.TextField(default='')),
                ('answerC', models.TextField(default='')),
                ('answerD', models.TextField(default='')),
                ('corrAns', models.CharField(default='', max_length=1)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Exam')),
            ],
        ),
        migrations.DeleteModel(
            name='Posst',
        ),
    ]
