# Generated by Django 3.0.7 on 2020-06-23 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20200613_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('fullName', models.TextField(default='', max_length=50)),
                ('birthDate', models.TextField(default='', max_length=10)),
                ('address', models.TextField(default='', max_length=100)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
