# Generated by Django 3.0.7 on 2020-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='fullName',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='info',
            name='lastName',
            field=models.TextField(default='', max_length=100),
        ),
    ]
