# Generated by Django 3.0.7 on 2020-06-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200623_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.TextField(default='', max_length=6),
        ),
    ]
