# Generated by Django 3.0.7 on 2020-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200623_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='birthDate',
            field=models.DateField(default=''),
        ),
    ]
