# Generated by Django 3.0.7 on 2020-06-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200623_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
