# Generated by Django 3.0.7 on 2020-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200623_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
