# Generated by Django 3.0.6 on 2020-07-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200623_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
