# Generated by Django 3.0.7 on 2020-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200623_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
