# Generated by Django 3.0.6 on 2020-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_exam_datecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='dateCreate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
