# Generated by Django 3.0.6 on 2020-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200707_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='dateCreate',
            field=models.DateField(blank=True, default='2020-07-07 07:04:19'),
        ),
    ]
